task2
VadimShkedov/fortechLearn pull request #2
Opened 2023-09-22 06:10 UTC by VadimShkedov

2023-09-25 07:23 UTC, baklanovairina requested changes

2023-09-25 07:23 UTC, baklanovairina commented on task2.js
> +    const settedAnotherArrays = []
и снова глагол в переменной

2023-09-25 07:23 UTC, baklanovairina commented on task2.js
> +                if (valueAnotherArray == valueMainArray) {
всегда используем только строгое равенство

2023-09-25 07:23 UTC, baklanovairina commented on task2.js
> +    arrs.forEach((value) => settedAnotherArrays.push(new Set(value)))
зачем ты при каждой итерации вызываешь new Set?

2023-09-25 08:13 UTC, VadimShkedov commented on task2.js
> +    arrs.forEach((value) => settedAnotherArrays.push(new Set(value)))
здесь удаляются все повторяющиеся элементы и задача сводится к тому, чтобы найти хотя бы один элемент этого массива

2023-09-29 12:46 UTC, baklanovairina requested changes

2023-09-29 12:46 UTC, baklanovairina commented on task2.js
> +  arrs.forEach((value) => uniqueAnotherArrays.push(new Set(value)));
ну мы уже про это говорили: new Set выполняется каждый раз при новой итерации, какой в этом смысл, мы только время тратим? Почему его 1 раз нельзя сделать?

2023-09-29 12:46 UTC, baklanovairina commented on task2.js
> +  let finalArray = [];
это const

2023-09-29 12:46 UTC, baklanovairina commented on task2.js
> +    for (let anotherArray of uniqueAnotherArrays) {
отступ в одну строку перед for

2023-09-29 12:46 UTC, baklanovairina commented on task2.js
> +  return finalArray;
отступ в одну строку перед return

2023-09-29 16:43 UTC, merged